name = "issoubot"
type = "javascript"
account_id = "da17fb43eebd31597a932433ccee9b14"

# This field specifies that the Worker
# will be deployed to a *.workers.dev domain
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
